[project]
name = "emergency_flow"
version = "0.1.0"
description = "emergency_flow is an structured flow capable of managing fire emergency situations"
authors = [{ name = "Your Name", email = "you@example.com" }]
requires-python = ">=3.10,<=3.13"
dependencies = [
    "crewai[tools]>=0.79.4,<1.0.0",
]

[project.scripts]
kickoff = "emergency_flow.main:kickoff"
plot = "emergency_flow.main:plot"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
