drive_back_to_work_station:
  description: >
    After finishing the detailed report on the people rescued, 
    traffic_driver will proceed to return to the traffic office to submit the data and complete the necessary paperwork
  expected_output: >
    Print the time elapsed from the accident to the traffic office registration.
    Print total number of people rescued
  agent: traffic_driver

drive_to_emergency_site:
  description: >
    With the OSMnx Shortest Path Tool, 
    calculate the most efficient route from the origin to the destination using the 
    'valencia.graphml' map file in {graph_path} . The destination coordinates are provided in 
    {phone_call_details} (latitude and longitude). Ensure the route is optimized for 
    the shortest distance or time.
  expected_output: >
    Print the origin coordinates (longitude and latitude)
    Print the destination coordinates (longitude and latitude) from {phone_call_details}
    Print the estimated travel distance between the two points
    Ensure the output is formatted for readability.
  agent: traffic_driver

rescue_support:
  description: >
    Assist in rescuing the trapped individuals, providing support 
    while the firefighting team handles extinguishing the fire and ensuring the safety of the area.
  expected_output: >
    print detailed list of persons who have been rescued
  agent: rescue_supporter
