secure_zone:
  description: >
    Use the valencia.graphml file and the OSMnx Shortest Path Tool, get the locations to secure 
    (longitude and latitude.
  expected_output: >
     A detailed list of the zones.
  agent: rescue_supporter

drive_to_emergency_site:
  description: >
    With the OSMnx Shortest Path Tool, 
    calculate the most efficient route from the origin to the destination using the 
    'valencia.graphml' map file in {graph_path} . The destination coordinates are provided in 
    {phone_call_details} (latitude and longitude). Ensure the route is optimized for 
    the shortest distance or time.
  expected_output: >
    Print the following information to the terminal:
    - The origin coordinates (longitude and latitude)
    - The destination coordinates (longitude and latitude) from {phone_call_details}
    - The estimated travel distance between the two points
    Ensure the output is formatted for readability.
  agent: traffic_driver

rescue_support:
  description: >
    Assist in rescuing the trapped individuals, providing support 
    while the firefighting team handles extinguishing the fire and ensuring the safety of the area.
  expected_output: >
    print detailed list of persons who have been rescued
  agent: rescue_supporter
